### ISSUE TITLE
HELP! May I use silkworm evm as a lib plugin in erigon? 

### ISSUE THREAD

**Issue by hitdavid** [erigontech/silkworm#1648]
I guess silkworm may have an EVM implement with better performance than erigon.
May I use silkworm EVM core as a plugin of erigon?
How can I start? Thanks

**Comment by yperbasis** [comment]
We've added support of execution with Silkworm in https://github.com/ledgerwatch/erigon/pull/8353. Check it out using flags `--silkworm.path` and `--silkworm.exec`, but please bear in mind that it's very experimental and we're actively working on it. cc @canepat

**Comment by hitdavid** [comment]
> We've added support of execution with Silkworm in [ledgerwatch/erigon#8353](https://github.com/ledgerwatch/erigon/pull/8353). Check it out using flags `--silkworm.path` and `--silkworm.exec`, but please bear in mind that it's very experimental and we're actively working on it. cc @canepat

Thanks a lot. I'll try it.

**Comment by canepat** [comment]
@hitdavid I'm closing this as answered, feel free to reopen.

BTW more information about how Silkworm can be used for block execution in Erigon is in [our README](https://github.com/erigontech/silkworm/blob/master/README.md#about-silkworm-for-erigon-aka-erigon).
