### ISSUE TITLE
upgrade GRPC

### ISSUE THREAD

**Issue by battlmonstr** [erigontech/silkworm#2079]
The GRPC version we use (1.48.0) is 2 years old.

We probably should upgrade to the version that is available in conan and compatible with asio-grpc from conan. This way we can utilize the prebuilt binaries (GRPC is not fast to build from scratch).

At the moment the latest asio-grpc on conan is 2.9.2 and it depends on grpc/1.54.3 and boost/1.83.0

The conan libraries that need to be updated together:
* asio-grpc
* boost (dependency of asio-grpc)
* grpc
* protobuf
* abseil
* openssl
* zlib

Even though older openssl and zlib are compatible with grpc, conancenter has grpc binary with a particular version of openssl and zlib, so not updating them makes this binary unavailable.

To list all the dependencies and compatible versions run:

    conan info asio-grpc/2.9.2@

Draft PR:
https://github.com/erigontech/silkworm/pull/1619

**Comment by canepat** [comment]
Closed by #1619
