### ISSUE TITLE
Implement EIP-2935: Serve historical block hashes from state

### ISSUE THREAD

**Issue by canepat** [erigontech/silkworm#2121]
[EIP-2935](https://eips.ethereum.org/EIPS/eip-2935) is included into [Pectra](https://eips.ethereum.org/EIPS/eip-7600)
https://github.com/ledgerwatch/erigon/pull/9991

**Comment by chfast** [comment]
I will implement this in evmone for testing but maybe I could expose "system calls" to Silkworm too.
