### ISSUE TITLE
fast clang-tidy for PRs

### ISSUE THREAD

**Issue by battlmonstr** [erigontech/silkworm#2324]
A clang-tidy job takes 50 min which is not feasible to run locally or on PRs.
With more strict policies we are getting breakage more often.

Ideas:
1. research options for running clang-tidy on PRs (e.g. [clang-tidy-diff.py](https://github.com/microsoft/clang-tools-extra/blob/master/clang-tidy/tool/clang-tidy-diff.py)).
2. if there are no good fast options, consider making clang-tidy job run monthly to avoid PR churn.
3. check some typical mistakes, and automate fixing them with clang-tidy fixes.

**Comment by battlmonstr** [comment]
CC @chfast

**Comment by chfast** [comment]
Silkworm is using CMake's integration of clang-tidy:
- https://github.com/erigontech/silkworm/blob/c647e16c4e384641dba3e7a6cf772a668da5deae/CMakeLists.txt#L95
- https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_CLANG_TIDY.html

This is actually suitable for local incremental builds: i.e. it will only check the files being built. However, this may be still annoying.

There is an option to profile where clang-tidy spends its time (`--enable-check-profile` but read the [docs](https://clang.llvm.org/extra/clang-tidy/). From my experience most of the checks are fast but some are very slow. This information may help making decision of removing some check or moving them to nightly only.

Also the Clang Analyzer is part of clang-tidy (although it is disabled in Silkworm https://github.com/erigontech/silkworm/blob/master/.clang-tidy#L22). This is usually slow too, but may be good to run as a separate nightly job. 

The [clang-tidy-diff](https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clang-tidy/tool/clang-tidy-diff.py) is the upstream tool so it should be in good shape. I have it installed on my machine as a part of LLVM distribution.
