### ISSUE TITLE
silkworm_capi_test: failure on macOS after decreasing execution batch size

### ISSUE THREAD

**Issue by canepat** [erigontech/silkworm#2389]
After PR #2308, which decreased the batch size in block execution tests, some C API unit tests started to fail only on [macOS](https://github.com/erigontech/silkworm/actions/runs/10990981472/job/30512377832).

It seems to be somewhat related to [this](https://github.com/llvm/llvm-project/issues/49036), but in a different context so needs further investigation.

#2388 skips such tests to restore clean build

**Comment by battlmonstr** [comment]
fixed by https://github.com/erigontech/silkworm/pull/2412
