### ISSUE TITLE
Call Traces in Execution

### ISSUE THREAD

**Issue by AndreaLanfranchi** [erigontech/silkworm#581]
Actually Silkworm does not implement CallTraces collection.
To be decided whether to implement it now to keep strict db binary compatibility with Erigon or to postpone to a later moment

**Comment by AndreaLanfranchi** [comment]
To be postponed.
Either wait for Erigon's 2 implementation (which might be more efficient) or postpone till we're at a stage when we do need to use `trace_filters`

**Comment by canepat** [comment]
Done in #1878
