### ISSUE TITLE
Block Transaction's From field should be protected

### ISSUE THREAD

**Issue by AndreaLanfranchi** [erigontech/silkworm#661]
Actually you can set an arbitrary sender address to a transaction (simply providing a value for the optional) but this can lead to data corruption as the provided value might not match the signature of the transaction.
To be done : make `from` a getter function from private field
Wrt #660

**Comment by gurukamath** [comment]
Would this mean that the only way to set the `from` field is through `recover_sender()`? If so, won't a lot of test cases need to be re-written? For e.g. [this](https://github.com/torquem-ch/silkworm/blob/4b2d3c7d795e828898befd355dae8d3d8b044bab/core/silkworm/execution/processor_test.cpp#L421)

I don't see the proper values of r, s, v set in some of these tests to be able to recover the sender.

**Comment by canepat** [comment]
Done in #1711
