### ISSUE TITLE
Package-manage GMP

### ISSUE THREAD

**Issue by battlmonstr** [erigontech/silkworm#672]
Currently there are 2 package managers:
* git + cmake (via git submodules and cmake scripts)
* hunter

GMP is not included there, and has to be installed manually.

It would be nice to integrate it into the common setup by either:
* checking it to git, having a submodule and a related cmake script
* or making a hunter script wrapping it, and bringing it using hunter

**Comment by AndreaLanfranchi** [comment]
Actually package managers are 3 : there is also vcpckg for windows (is needed to install and use MPIR instead of GMP on windows)

**Comment by canepat** [comment]
Closed by #1150 and #1184
