### ISSUE TITLE
Performance improvements in first sync

### ISSUE THREAD

**Issue by canepat** [erigontech/silkworm#774]
Log from the first-sync test executed in date 2022-09-28:

https://erigon5900c.weblogix.it/er-9.log
(copy here [er.log.txt](https://github.com/torquem-ch/silkworm/files/9666163/er.log.txt) )

and final report:

![photo_2022-09-28_15-41-39](https://user-images.githubusercontent.com/16927169/192794569-d67510fd-7147-4368-8a51-e9b3f9cd1850.jpg)

The comparison report shows that optimization work can be done to improve the following stages:

- [ ] Log Index

**Comment by AndreaLanfranchi** [comment]
Probably you mean "Log Index" and "TxLookup"
Stage "History Index" is on par with Erigon Stable and a lot faster then
the others (note that it binds Account History Index and Storage History
Index together)

- Erigon Stable : 2:22 + 3:35 == 5:57
- Erigon Devel : 2:39 + 4:04 == 6:43
- Erigon Alpha : 2:41 + 4:10 = 6:51
- Silkworm : 5:53

To me it seems only Log Index is slower

**Comment by canepat** [comment]
Right, I just compared `History Index` with one line instead of two on the Erigon side.
