### ISSUE TITLE
Please support Ethereum fair and Ethereum Proof of work and thus don’t remove support for proof of work from the code !

### ISSUE THREAD

**Issue by ytrezq** [erigontech/silkworm#802]
Those chains are forks of the Ethereum mainnet [where the merge didn’t happen](https://ethereumpow.org/) and this still have their own execution layer.
Though of course, they changed the chainid. They also managed to be listed on many exchanges where they can be exchanged directly for fiat.

**Comment by yperbasis** [comment]
Sorry, we have no intention of supporting PoW networks.
